### PR TITLE
Rights Firebase & Backend

### PR DESCRIPTION
**Pull request by manukastratta**
The rights section no longer relies on dummy data! As the app is loaded, the data is fetched from firebase and stored in the static class variable, ImportedData. The other screens and components use this class to grab the data that needs to be displayed. 

New additions:
- Implemented the ImportedData class in the FetchRightsData.js file, which was the bulk of the firebase fetching work. The loadAllData() async function makes a request to firebase and fetches the rights, subrights, categories, etc and stores them in class variables/arrays. The ImportedData class contains getters and setters to access these variables storing the data. 
- /!\ Note: for this to work, you will need to include create a file in constants/MyApiKeys that simply contains the firebase API key / secret information. I added it to the .gitignore so that the api keys wouldn't be exposed here. 
- In App.js, implemented async function which calls loadAllData() in ImportedData class as soon as the App is loaded for the first time. This means that the data is only updated when the app is closed / reopened, which should be fine as the rights data will not be changing often / when the user is using the app. 
- Created the PushDummyData.js file that is useful to push the dummy data to the firebase, which can be faster / more convenient than using the firebase UI sometimes.

Other changes:
- In all screens and components, changed the way the data to be is displayed (no longer from dummy data, but from the ImportedData class variable). For example, instead of importing and using RIGHTSCATEGORIES from dummy data, we do ImportedData.getRightsCategories() to get the rights categories to be displayed.
- Added a bit more fake/filler data for demo purposes

Left TODO:
- Images are all stored locally as of now. I need to create urls for the organization images, but will keep the rights icons images stored locally on the app as they will probably not change and we don't need to be fetching them from firebase (which could slow the app down by fetching images unnecessarily). 
- Figure out what to do with the keys. For now, we're still using the custom id's we have, like "c1", "c2", etc. Might be interesting to see how we can use the Firebase ids. Any suggestions welcome,
- Implement more error-checking, in case certain fields are corrupt or missing. Eg. no "learn mores" field (I have a quick check for now, might want to make it more robust)

### CODE REVIEW

**Comment by angel-pan** [comment]
Looks good! Seems to work the same as the dummy-data. A minor thing that we might want to change is the package.json file. Currently firebase isn't added as a dependency so if someone does not have firebase on their machine locally they would need to install it separately.

**Comment by manukastratta** [comment]
> Looks good! Seems to work the same as the dummy-data. A minor thing that we might want to change is the package.json file. Currently firebase isn't added as a dependency so if someone does not have firebase on their machine locally they would need to install it separately.

Good point, thanks!

**Comment by angel-pan** [comment]
It looks like at the moment it just adds data to the database but it doesn't replace. So when you want to push something to the database from dummy data you uncomment the import in App.js. That's why when I was testing it earlier it didn't replace the subrights stuff with orgs stuff but just added it to the bottom. I don't think it would be too difficult to change the functionality to replace instead but I'm not sure if that's be a feature we would want

**Comment by manukastratta** [comment]
> Looks really good! Works fine on my phone. Code also looks clean. Are you pushing data to the firebase each time the app runs - in the sense of syncing the dummy-data with firebase? I added some fake rights to the firebase for testing purposes while working on the web portal, and they're gone now, so I'm wondering if you manually took them down, or that'll happen programmatically all the time?

Hey! I'm not syncing the dummy data with the firebase automatically. I just have the file so that I can call the function and push the dummy data to the firebase when I want to, but it's NOT done every time the app is run.
Regarding the fake rights, I did delete 2 fake rights categories manually (sorry, didn't know you were using them). But in general, if you need fake rights, can you use a fakeRights firebase branch/section instead of the real thing? Because the reason I deleted the 2 fake rights was because it was throwing an error when the rights categories screen was loading (because the images weren't passed in properly), so I had to delete them to get rid of the error. But yeah, if you're testing, I think it's better if you don't use the true rightsCategories section of firebase.

**Comment by manukastratta** [comment]
> It looks like at the moment it just adds data to the database but it doesn't replace. So when you want to push something to the database from dummy data you uncomment the import in App.js. That's why when I was testing it earlier it didn't replace the subrights stuff with orgs stuff but just added it to the bottom. I don't think it would be too difficult to change the functionality to replace instead but I'm not sure if that's be a feature we would want

Exactly, you need to uncomment the import in App.js and maybe another getData function in the pushDummyData file to push the data to firebase. @RyanRTJJ Just making sure you guys understand that I'm not syncing up the dummy data with the firebase each time. 
Regarding the replacing this, yes Angel you're right, it doesn't replace but just adds at the bottom. That might be something we want to change, but for now I'll leave it as it is, because it could be dangerous to completely replace the firebase data if we push some dummy data by accident.

**Pull request merged**
